---
title: "Robust tools 05: SThe programming of aRt"
output: html_notebook
---


https://robust-tools.djnavarro.net/

```{r}
library(tidyverse)
library(ambient) # intall of this is currently busted
library(scico)
library(here)
```

## Parameters

```{r}
art_par <- list(
  seed = 2, 
  n_paths = 500,
  n_steps = 80,
  sz_step = 200,
  sz_slip = 200
)
```

## Setup canvas

```{r}

set.seed(seed = art_par$seed)

state <- tibble(
  x = runif(n = art_par$n_paths,
            min = 0,
            max = 2),
  y = runif(n = art_par$n_paths,
            min = 0,
            max = 2),
  z= runif(n = art_par$n_paths,
            min = 0,
            max = 1)
)

state %>% ggplot(aes(x,y, colour = z)) + geom_point()


# Incluse the path id and the step id in the state
state <- state %>%
  mutate(
    path_id = 1:art_par$n_paths,
    step_id = 1
  )

```
## Setup data structure

```{r}
art_dat <- state
```

## Make the art in a loop

```{r}
stop_painting <- FALSE

while (stop_painting == FALSE) {
  # do some patinting
  
  ## make a step
  
  step <- curl_noise(
    generator = gen_simplex,
    x = state$x,
    y = state$y,
    z = state$z,
    seed = c(1,1,1) * art_par$seed
  )
  
  
  state <- state %>%
    mutate(
      x = x + (step$x / 10000) * art_par$sz_step ,
      y = y + (step$y / 10000) * art_par$sz_step,
      z = z + (step$z / 10000) * art_par$sz_slip,
      step_id = step_id + 1
    )
  
  # aappend the state to art_date
  art_dat <- bind_rows(art_dat, state)
  
  # print the current step
  current_step <- last(state$step_id)
 # print(current_step)
  
  # stop the painting if we the n_steps parameter
  if(current_step  == art_par$n_steps) {
    stop_painting <- TRUE
  }
  
} 


```


## Draw our picture
```{r, fig.asp=1}


art_pic <- art_dat %>%
  ggplot(
    aes(x,y,
        group = path_id,
        colour = z)
    ) +
  geom_path(size = 0.5, alpha = 0.5, show.legend = FALSE) +
  theme_void() +
  coord_equal() +
  scale_colour_scico(palette = "acton") +
  theme(plot.background = element_rect(fill = "gainsboro"),
        panel.background = element_rect(fill = "gainsboro"))

#art_pic



filename <- paste0("scrawl_",str_c(art_par, collapse = "-"),".png")

ggsave(
  filename = filename,
  path = here(),
  plot = art_pic,
  width = 10,
  height = 10,
  dpi = 300
  
)
```

